
  /*******************************************************************
  * EncryptPassword.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package com.nkhatho.leole.passwordgenerator;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;


public class EncryptPassword
{
    static final String SERVICE_NAME = "EncryptPassword";

    private static EncryptPassword ourInstance = new EncryptPassword();

    private EncryptPassword(  )
    {
    }

    public static EncryptPassword getInstance()
    {
        return ourInstance;
    }

    public void getEcryptedPasswordAsync(String word, float number, AsyncCallback<Object> callback)
    {
        Object[] args = new Object[]{word, number};
        Backendless.CustomService.invoke( SERVICE_NAME, "getEcryptedPassword", args, Object.class, callback);
    }
    
}
